const diseasesData = [
    { name: "Abcès", category: "Infectieuse" },
    { name: "Acné", category: "Dermatologique" },
    { name: "Alzheimer (maladie d’)", category: "Neurologique" },
    { name: "Anémie", category: "Cardiovasculaire" },
    { name: "Angine", category: "Infectieuse" },
    { name: "Appendicite", category: "Digestive" },
    { name: "Arthrite", category: "Musculo-squelettique" },
    { name: "Asthme", category: "Respiratoire" },
    { name: "Athérosclérose", category: "Cardiovasculaire" },
    { name: "Autisme", category: "Neurologique" },
    { name: "Bactériémie", category: "Infectieuse" },
    { name: "BPCO (bronchopathie chronique obstructive)", category: "Respiratoire" },
    { name: "Bronchite", category: "Respiratoire" },
    { name: "Brucellose", category: "Infectieuse" },
    { name: "Bursite", category: "Musculo-squelettique" },
    { name: "Cancer du sein", category: "Cancer" },
    { name: "Cancer du poumon", category: "Cancer" },
    { name: "Cancer colorectal", category: "Cancer" },
    { name: "Cataracte", category: "Autre" },
    { name: "Céphalée (maux de tête)", category: "Neurologique" },
    { name: "Cirrhose", category: "Digestive" },
    { name: "Coqueluche", category: "Infectieuse" },
    { name: "Covid‑19", category: "Infectieuse" },
    { name: "Crohn (maladie de)", category: "Chronique" },
    { name: "Cystite", category: "Infectieuse" },
    { name: "Dengue", category: "Infectieuse" },
    { name: "Dépression", category: "Neurologique" },
    { name: "Dermatite atopique", category: "Dermatologique" },
    { name: "Diabète de type 1", category: "Métabolique" },
    { name: "Diabète de type 2", category: "Métabolique" },
    { name: "Diarrhée infectieuse", category: "Infectieuse" },
    { name: "Diphterie", category: "Infectieuse" },
    { name: "Dysenterie", category: "Infectieuse" },
    { name: "Dyslipidémie", category: "Métabolique" },
    { name: "Dystrophie musculaire", category: "Musculo-squelettique" },
    { name: "Eczéma", category: "Dermatologique" },
    { name: "Embolie pulmonaire", category: "Cardiovasculaire" },
    { name: "Endométriose", category: "Autre" },
    { name: "Epilepsie", category: "Neurologique" },
    { name: "Escherichia coli infection", category: "Infectieuse" },
    { name: "Esophagite", category: "Digestive" },
    { name: "Etat grippal", category: "Infectieuse" },
    { name: "Étourdissements (vertiges)", category: "Neurologique" },
    { name: "Érysipèle", category: "Infectieuse" },
    { name: "Érythème infectieux", category: "Infectieuse" },
    { name: "Fibromyalgie", category: "Musculo-squelettique" },
    { name: "Fibrose pulmonaire", category: "Respiratoire" },
    { name: "Fièvre jaune", category: "Infectieuse" },
    { name: "Fièvre typhoïde", category: "Infectieuse" },
    { name: "Fracture osseuse", category: "Musculo-squelettique" },
    { name: "Gastrite", category: "Digestive" },
    { name: "Gastro‑entérite", category: "Digestive" },
    { name: "Glaucome", category: "Autre" },
    { name: "Goutte", category: "Métabolique" },
    { name: "Grippe saisonnière", category: "Infectieuse" },
    { name: "Hépatite A", category: "Infectieuse" },
    { name: "Hépatite B", category: "Infectieuse" },
    { name: "Hépatite C", category: "Infectieuse" },
    { name: "Hernie discale", category: "Musculo-squelettique" },
    { name: "Hypertension artérielle", category: "Cardiovasculaire" },
    { name: "Hypothyroïdie", category: "Métabolique" },
    { name: "Hyperthyroïdie", category: "Métabolique" },
    { name: "Hypoglycémie", category: "Métabolique" },
    { name: "Hypercholestérolémie", category: "Métabolique" },
    { name: "Hémorroïdes", category: "Digestive" },
    { name: "Infection urinaire", category: "Infectieuse" },
    { name: "Influenza (grippe)", category: "Infectieuse" },
    { name: "Insuffisance cardiaque", category: "Cardiovasculaire" },
    { name: "Insuffisance rénale chronique", category: "Chronique" },
    { name: "Insomnie", category: "Neurologique" },
    { name: "Intoxication alimentaire", category: "Infectieuse" },
    { name: "Irritable bowel syndrome (syndrome de l’intestin irritable)", category: "Digestive" },
    { name: "Ischémie myocardique", category: "Cardiovasculaire" },
    { name: "Infections sexuellement transmissibles (IST)", category: "Infectieuse" },
    { name: "Impétigo", category: "Infectieuse" },
    { name: "Jaunisse", category: "Autre" },
    { name: "Jet lag (trouble du rythme circadien)", category: "Neurologique" },
    { name: "Jambes sans repos (syndrome)", category: "Neurologique" },
    { name: "Jéjuno‑iléite", category: "Digestive" },
    { name: "Juvenile idiopathic arthritis", category: "Musculo-squelettique" },
    { name: "Kératite", category: "Autre" },
    { name: "Kyste ovarien", category: "Autre" },
    { name: "Kyste synovial", category: "Musculo-squelettique" },
    { name: "Kawasaki (maladie de)", category: "Infectieuse" },
    { name: "Kwashiorkor", category: "Métabolique" },
    { name: "Leptospirose", category: "Infectieuse" },
    { name: "Leucémie", category: "Cancer" },
    { name: "Lupus érythémateux systémique", category: "Chronique" },
    { name: "Lymphome hodgkinien", category: "Cancer" },
    { name: "Lymphome non hodgkinien", category: "Cancer" },
    { name: "Malaria (paludisme)", category: "Infectieuse" },
    { name: "Maladie de Parkinson", category: "Neurologique" },
    { name: "Maladie de Basedow", category: "Métabolique" },
    { name: "Maladie de Charcot (SLA)", category: "Neurologique" },
    { name: "Maladie de Ménière", category: "Neurologique" },
    { name: "Maladie de Wilson", category: "Métabolique" },
    { name: "Maladie cœliaque", category: "Chronique" },
    { name: "Maladie coronarienne", category: "Cardiovasculaire" },
    { name: "Maladie rénale chronique", category: "Chronique" },
    { name: "Méningite", category: "Infectieuse" },
    { name: "Néphrite", category: "Chronique" },
    { name: "Névralgie", category: "Neurologique" },
    { name: "Névrite optique", category: "Neurologique" },
    { name: "Nodule thyroïdien", category: "Métabolique" },
    { name: "Norovirus infection", category: "Infectieuse" },
    { name: "Obésité", category: "Métabolique" },
    { name: "Otite moyenne", category: "Infectieuse" },
    { name: "Ostéoporose", category: "Musculo-squelettique" },
    { name: "Ostéomyélite", category: "Infectieuse" },
    { name: "Oxyurose", category: "Infectieuse" },
    { name: "Pancréatite", category: "Digestive" },
    { name: "Paralysie cérébrale", category: "Neurologique" },
    { name: "Peste", category: "Infectieuse" },
    { name: "Pharyngite", category: "Infectieuse" },
    { name: "Pneumonie", category: "Respiratoire" },
    { name: "Polio (poliomyélite)", category: "Infectieuse" },
    { name: "Psoriasis", category: "Dermatologique" },
    { name: "Pyélonéphrite", category: "Infectieuse" },
    { name: "Pyrosis (reflux gastrique)", category: "Digestive" },
    { name: "Q‑fever (fièvre Q)", category: "Infectieuse" },
    { name: "Quadriplégie", category: "Neurologique" },
    { name: "Quératose actinique", category: "Dermatologique" },
    { name: "Quératoconjonctivite", category: "Autre" },
    { name: "Quiste pilonidal", category: "Autre" },
    { name: "Rage", category: "Infectieuse" },
    { name: "Rachitisme", category: "Métabolique" },
    { name: "Rectocolite hémorragique", category: "Digestive" },
    { name: "Rétinopathie diabétique", category: "Métabolique" },
    { name: "Rhinite allergique", category: "Respiratoire" },
    { name: "Rosacée", category: "Dermatologique" },
    { name: "Rubéole", category: "Infectieuse" },
    { name: "Rhumatisme articulaire aigu", category: "Infectieuse" },
    { name: "Rhumatoïde (polyarthrite)", category: "Musculo-squelettique" },
    { name: "Rickets", category: "Métabolique" },
    { name: "Sarcoïdose", category: "Chronique" },
    { name: "Scarlatine", category: "Infectieuse" },
    { name: "Sclérose en plaques", category: "Neurologique" },
    { name: "Scoliose", category: "Musculo-squelettique" },
    { name: "Septicémie", category: "Infectieuse" },
    { name: "Sida (VIH)", category: "Infectieuse" },
    { name: "Sinusite", category: "Infectieuse" },
    { name: "Syphilis", category: "Infectieuse" },
    { name: "Syndrome métabolique", category: "Métabolique" },
    { name: "Syndrome néphrotique", category: "Chronique" },
    { name: "Tétanos", category: "Infectieuse" },
    { name: "Thrombose veineuse profonde", category: "Cardiovasculaire" },
    { name: "Thyroïdite", category: "Métabolique" },
    { name: "Toxoplasmose", category: "Infectieuse" },
    { name: "Tuberculose", category: "Infectieuse" },
    { name: "Tumeur bénigne", category: "Autre" },
    { name: "Typhus", category: "Infectieuse" },
    { name: "Tendinite", category: "Musculo-squelettique" },
    { name: "Trichomonase", category: "Infectieuse" },
    { name: "Trisomie 21", category: "Autre" },
    { name: "Ulcère gastrique", category: "Digestive" },
    { name: "Ulcère duodénal", category: "Digestive" },
    { name: "Urticaire", category: "Dermatologique" },
    { name: "Uvéite", category: "Autre" },
    { name: "Urolithiase (calculs urinaires)", category: "Digestive" },
    { name: "Varicelle", category: "Infectieuse" },
    { name: "Varices", category: "Cardiovasculaire" },
    { name: "Variole", category: "Infectieuse" },
    { name: "Vascularite", category: "Cardiovasculaire" },
    { name: "Verrues", category: "Dermatologique" },
    { name: "Vertige paroxystique bénin", category: "Neurologique" },
    { name: "Vitiligo", category: "Dermatologique" },
    { name: "Vulvovaginite", category: "Infectieuse" },
    { name: "Virus respiratoire syncytial (VRS)", category: "Infectieuse" },
    { name: "Waldenström (macroglobulinémie de)", category: "Cancer" },
    { name: "Wegener (granulomatose de)", category: "Infectieuse" },
    { name: "Whipple (maladie de)", category: "Infectieuse" },
    { name: "Wilson (maladie de)", category: "Métabolique" },
    { name: "Warts (verrues génitales)", category: "Infectieuse" },
    { name: "Xeroderma pigmentosum", category: "Dermatologique" },
    { name: "Xanthome", category: "Dermatologique" },
    { name: "Xérose cutanée", category: "Dermatologique" },
    { name: "Xylophagie (pica rare)", category: "Autre" },
    { name: "Xiphoïdite", category: "Musculo-squelettique" },
    { name: "Yersiniose", category: "Infectieuse" },
    { name: "Yeux secs (syndrome)", category: "Autre" },
    { name: "Yaws (pian)", category: "Infectieuse" },
    { name: "Yellow fever (fièvre jaune)", category: "Infectieuse" },
    { name: "Yeast infection (candidose)", category: "Infectieuse" },
    { name: "Zona (herpès zoster)", category: "Infectieuse" },
    { name: "Zoonose bactérienne", category: "Infectieuse" },
    { name: "Zygomycose", category: "Infectieuse" },
    { name: "Zika (virus)", category: "Infectieuse" },
    { name: "Zollinger‑Ellison (syndrome)", category: "Métabolique" },
    { name: "Abcès dentaire", category: "Infectieuse" },
    { name: "Allergie alimentaire", category: "Autre" },
    { name: "Allergie respiratoire", category: "Respiratoire" },
    { name: "Anévrisme aortique", category: "Cardiovasculaire" },
    { name: "Arthrose", category: "Musculo-squelettique" },
    { name: "Ballonnements chroniques", category: "Digestive" },
    { name: "Colique néphrétique", category: "Digestive" },
    { name: "Déficit en vitamine D", category: "Métabolique" },
    { name: "Maladie des gencives (gingivite/parodontite)", category: "Infectieuse" },
    { name: "Trouble anxieux généralisé", category: "Neurologique" }
];

window.diseasesData = diseasesData;
